# Introdução

O Cadastro Nacional de Condenações Cíveis por Ato de Improbidade Administrativa 
e Inelegibilidade
[(CNIA)](http://www.cnj.jus.br/sistemas/certidoes/20650-cadastro-nacional-de-condenacoes-civeis-por-ato-de-improbidade-administrativa-cnia)
é uma base de dados controlada pelo Conselho Nacional de Justica (CNJ). A partir
dessa ferramenta, é possível consultar os atos da Administraçao que causaram 
danos morais ou materiais ao Estado, através do registro de pessoas públicas 
júridicas ou físicas que foram condenadas judicialmente.

O problema é que, infelizmente, o acesso à base do CNC é limitado. Como o site 
faz uso de captchas em consultas individuais, não é possível obter 
automaticamente uma lista de todos os processos de improbidade contidos na base,
o que impede o cálculo de estatísticas básicas sobre o problema e o devido 
acompanhamento dos processos.

O presente trabalho tem como objetivo principal solucionar este problema. A 
partir da construção dos programas para extração de dados, serão levantadas 
estatísticas básicas sobre os processos contidos no CNC, o que possibilitará 
maior conhecimento sobre as ações de improbidade administrativa no Brasil.

Na fase inicial, realizamos o download e arrumação dos dados. A metodologia para
extração será descrita na próxima Seção. Todos os códigos utilizados para 
extração dos dados são públicos e podem ser acessados [neste 
link](https://github.com/abjur/cnc).
